/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.engcia;
// package must be defined in packages from kmodule.xml file

//list any import classes here.
import org.engcia.model.Sensor;
import org.engcia.model.Hypothesis;
import org.engcia.model.Conclusion;

//declare any global variables here

query "Conclusions"
	$conclusion : Conclusion()
end

rule "Rule Thermal Missmatch Sensors missmatch"
	when
	    $sensor: Sensor(name matches ".*_Thermal_.*", value < 45)
	then
		Conclusion c = new Conclusion(Conclusion.SensorBadValue, $sensor.getName());
		insert(c);
end


